#tomcat端口
server:
 port: 8080
#数据连接
spring:
  datasource:
    url: jdbc:mysql://49.234.229.34:3306/SimpleCreate?serverTimezone=UTC&userUnicode=true&characterEncoding=utf-8
    username: wanghui
    password: wanghui.19980519
    driverClassName: com.mysql.cj.jdbc.Driver
  redis:
    host: 49.234.229.34
    port: 12345
    password: wanghui.19980519
mybatis:
  #Mybatis扫描
  mapper-locations: classpath:mapper/*.xml
  #起别名。可省略写mybatis的xml中的resultType的全路径
  type-aliases-package: club.simplecreate.pojo

logging:
 level:
  club.simplecreate.dao: debug